apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testingapp
  template:
    metadata:
      labels:
        app: testingapp
    spec:
      containers:
      - name: testingapp
        image: testingapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080